### PR TITLE
ci: use Temurin distributions

### PR DESCRIPTION
**Pull request by yeikel**
Host runners include Temurin by default as part of the [hosted tool cache ](https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#hosted-tool-cache)

Using Temurin speeds up builds as there is no need to download and configure the Java SDK with every build.

### CODE REVIEW

**Comment by brharrington** [comment]
Looks like 15 is not available for Temurin, would likely need to bump that to 17 as it is the most recent LTS.

**Comment by yeikel** [comment]
> Looks like 15 is not available for Temurin, would likely need to bump that to 17 as it is the most recent LTS.

Does this project need to support Java 15?

**Comment by brharrington** [comment]
15 was not an LTS releases and is no longer supported, so it can be bumped to 17.

**Comment by yeikel** [comment]
> 15 was not an LTS releases and is no longer supported, so it can be bumped to 17.

I bumped it with d6340b29ab45205de8957c0e7a0df9e95889ed78

**Review by brharrington — APPROVED** [review]

**Pull request merged**
